apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  labels:
    app: order-service
data:
  SPRING_DATASOURCE_PASSWORD: cTVzT2w0R0pmNw==
  # Add or override other keys as needed for dev

