apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - namespace.yaml
  - ../../base
patches:
  - path: envvars-patch.yaml
    target:
      kind: Deployment
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
  - path: secret-patch.yaml
    target:
      kind: Secret
  - path: hpa-patch.yaml
    target:
      kind: HorizontalPodAutoscaler
  - path: resources-patch.yaml
    target:
      kind: Deployment
  - path: replicas-patch.yaml
    target:
      kind: Deployment
images:
  - name: order-service
    newTag: latest #v1.0.0
